name: Scrape TGJU
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Run scrape.js
        run: node scrape.js
      - name: Commit updated data
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/gold18.json
          git commit -m "Update gold18.json" || echo "No changes to commit"
          git push
